
import fsx from "fs-extra";
import mustache from "mustache";

const generator = require("../../package.json");

// disabling escape
mustache.escape = (s: string) => s

export const BANNER = `/**
* @generated by ${ generator.name }:${ generator.version }, do not modify manually!
*/`

type Options = { format?: boolean }

export function render<Context = {}>(
  template: string,
  context: Context,
  options?: Options,
): string {
  const content = mustache.render(template, context)
  return options?.format
    ? content.replace(/^\s*[\r\n]/gm, "")
    : content
}

export async function renderToFile<Context = {}>(
  file: string,
  template: string,
  context: Context,
  opts?: Options & { overwrite?: boolean },
): Promise<void> {

  if (opts?.overwrite === false) {
    if (await fsx.exists(file)) {
      return
    }
  }

  return fsx.outputFile(
    file,
    render(template, context, opts),
    "utf8"
  )

}

